[package]
name = "fullstack-workshop"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "api/lib",
    "api/shuttle",
    "shared"
]
resolver = "2"


[dependencies]
serde_json = "1.0.121"
tracing = "0.1.40"
